export const SET_DEFAULT_FILTER = 'SET_DEFAULT_FILTER';
export const GET_DEFAULT_FILTER = 'GET_DEFAULT_FILTER';
export const SET_FILTER = 'SET_FILTER';
export const GET_FILTER = 'GET_FILTER';
export const REM_FILTER = 'REM_FILTER';
export const ADD_SEARCH_CRITERIA = 'ADD_SEARCH_CRITERIA';